name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    # - name: Initialize Gradle project
    #   run: gradle init

    # - name: Configure build.gradle.kts
    #   run: |
    #     sed -i 's/sourceCompatibility = .*/sourceCompatibility = JavaVersion.VERSION_17/' build.gradle.kts
    #     sed -i 's/targetCompatibility = .*/targetCompatibility = JavaVersion.VERSION_17/' build.gradle.kts
    #     sed -i '/plugins {/a\    id("org.springframework.boot") version "3.0.4"\n    id("io.spring.dependency-management") version "1.1.0"' build.gradle.kts
    #     sed -i '/dependencies {/a\    implementation("org.springframework.boot:spring-boot-starter-web")\n    implementation("org.springframework.boot:spring-boot-starter-data-jpa")' build.gradle.kts

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: build/libs/*.jar